services: 
  app:
    image: node:alpine
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres1

  redis:
    image: redis:alpine
    volumes:
      - ./.data/redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres1:
    image: postgres:alpine
    volumes:
      - ./.data/postgres1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_1}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_1}
      - POSTGRES_DB=${POSTGRES_DB_1}
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:alpine
    volumes:
      - ./.data/postgres2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_2}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_2}
      - POSTGRES_DB=${POSTGRES_DB_2}
    ports:
      - "5433:5432"

  postgres3:
    image: postgres:alpine
    volumes:
      - ./.data/postgres3:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_3}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_3}
      - POSTGRES_DB=${POSTGRES_DB_3}
    ports:
      - "5434:5432"
